build:
	mpicc send_recv.c -o send_recv
	mpicc scatter_gather_max_arr.c -o scatter_gather_max_arr
	mpicc broadcast.c -o broadcast
	mpicc ex2.c -o ex2
	mpicc ex3.c -o ex3
	mpicc ex4.c -o ex4
clear:
	rm send_recv broadcast scatter_gather_max_arr ex2 ex3 ex4
